; --- Global Project Configuration ---
[platformio]
default_envs = esp32dev
description = Basic ESP32 firmware for telemetry upload and LED control


; --- Development Environment ---
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -I include
    -std=gnu++17

lib_deps =
    bblanchon/ArduinoJson@^7.4.2

check_tool = cppcheck
test_build_project_src = true

[env:native_test]
platform = native
test_framework = googletest
build_flags =
    -std=gnu++17
    -I include
test_build_project_src = false
