#ifndef FIRMWARE_ESP32_INCLUDE_SENSORS_MOCK_SENSOR_MODEL_HPP
#define FIRMWARE_ESP32_INCLUDE_SENSORS_MOCK_SENSOR_MODEL_HPP

#include <cmath>

namespace sensors
{

/**
 * @brief Deterministic environmental sample generated by the mock sensor model.
 */
struct MockSensorSample
{
    float temperature;
    float humidity;
};

/**
 * @brief Pure mock sensor model used by the firmware and native unit tests.
 *
 * This class is hardware-independent by design, which makes it suitable
 * for GTest-based validation on the host machine.
 */
class MockSensorModel
{
public:
    /**
     * @brief Generates a synthetic sample for a given elapsed time.
     *
     * @param elapsedSeconds Elapsed time in seconds since boot.
     * @return MockSensorSample Synthetic temperature and humidity values.
     */
    static MockSensorSample sampleAt(float elapsedSeconds)
    {
        return {
            24.5f + 3.5f * std::sin(elapsedSeconds / 18.0f),
            48.0f + 9.0f * std::sin(elapsedSeconds / 23.0f + 0.8f),
        };
    }
};

}  // namespace sensors

#endif  // FIRMWARE_ESP32_INCLUDE_SENSORS_MOCK_SENSOR_MODEL_HPP
